project-name: appmod-resorts-liberty
stack: docker-registry-default.devops-gse-state-458654-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud/kabanero-noauth/java-microprofile:0.2
