apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-29T16:44:53.794580
    commit.image.appsody.dev/author: Jhovany Gonzalez <Jhovany.Gonzalez@ibm.com>
    commit.image.appsody.dev/committer: Jhovany Gonzalez <Jhovany.Gonzalez@ibm.com>
    commit.image.appsody.dev/date: Mon Mar 9 15:35:58 2020 -0500
    commit.image.appsody.dev/message: first
    description: This image contains the Kabanero development stack for the java-microprofile
      collection
    distribution-scope: public
    image.opencontainers.org/created: "2020-03-10T10:51:27-05:00"
    image.opencontainers.org/documentation: https://github.com/jjgonz987/appmod-resorts-liberty-appsody
    image.opencontainers.org/revision: eff975f909c6fa769413f060ad079d40be89a1ea-modified
    image.opencontainers.org/source: https://github.com/jjgonz987/appmod-resorts-liberty-appsody/tree/master
    image.opencontainers.org/url: https://github.com/jjgonz987/appmod-resorts-liberty-appsody
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-microprofile
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1002.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "277"
    stack.appsody.dev/configured: docker-registry-default.devops-gse-state-458654-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud/kabanero-noauth/java-microprofile:0.2
    stack.appsody.dev/created: 2020-03-04T08:54:10-0600
    stack.appsody.dev/revision: 1580f608c12ace88ebdad12dadaafc32943114fd
    stack.appsody.dev/tag: docker-registry-default.devops-gse-state-458654-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud/kabanero-noauth/java-microprofile:0.2.18
    summary: Image for Kabanero java-microprofile development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-277
    vcs-ref: c42933bcdbf9f1c232e981a5e40de257c3534c8e
    vcs-type: git
    vendor: Kabanero
    version: 0.2.10
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: appmod-resorts-liberty
    stack.appsody.dev/version: 0.2.18
  name: appmod-resorts-liberty
spec:
  namespace: kabanero
  applicationImage: dev.local/appmod-resorts-liberty
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  stack: java-microprofile
  version: 1.0.0
